blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main_page, name = 'main_page'),
    path('home', views.home_page, name= 'home_page'),
    path('blog', views.post_list, name = 'post_list'),
    path('blog/post/<int:pk>/', views.post_detail, name='post_detail'),
    path('blog/post/new', views.post_new, name='post_new'),
    path('blog/post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('blog/post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('blog/post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('mypage',views.mypage, name='mypage'),
    path('member_del',views.member_del, name="member_del"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from rest_framework import routers
from blog import views


class HomeTemplateView(TemplateView):
  template_name = 'index.html'


router = routers.DefaultRouter()
router.register('post', views.PostView, 'post')
router.register('comment', views.CommentView, 'comment')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', HomeTemplateView.as_view(), name='home'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
      return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = not self.approved_comment
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):
  
    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.http.response import HttpResponse, JsonResponse
from django.utils import timezone
from .models import Post, Comment
from django.shortcuts import render,get_object_or_404,redirect
from .forms import PostForm, CommentForm
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from rest_framework import viewsets
from .serializers import PostSerializer
from .serializers import CommentSerializer

class PostView(viewsets.ModelViewSet):
    serializer_class = PostSerializer
    queryset = Post.objects.all()

class CommentView(viewsets.ModelViewSet):
    serializer_class = CommentSerializer
    queryset = Comment.objects.all()


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    form = CommentForm()
    return render(request, 'blog/post_detail.html', {'post': post, 'forms': form})

def main_page(request):
    m_views = 'hello'
    return render(request, 'blog/main_page.html', {'views': m_views})

def home_page(request):
    return render(request, 'blog/home_page.html')

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form })

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        # 사용권한 - 작성자만 이용 가능
        if(post.author == request.user):
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.published_date = timezone.now()
                post.save()
                return redirect('post_detail', pk=post.pk)
            return render(request, 'blog/post_edit.html', {'form': form })
        else:
            messages.error(request, "본인 게시글이 아닙니다.")
            return redirect('post_detail', pk=post.pk)
    else:
        if(post.author == request.user):
            form = PostForm(instance=post)
            return render(request, 'blog/post_edit.html', {'form': form })
        else:
            messages.error(request, "본인 게시글이 아닙니다.")
    return redirect('post_detail', pk=post.pk)

def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if(post.author == request.user):
        post.delete()
        return redirect('post_list')
    else:
        messages.error(request, "본인 게시글이 아닙니다.")
        return redirect('post_detail', pk=post.pk)

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.approve()
            comment.save()
            return HttpResponse(simplejson.dumps({"response":"Good"}))
            #return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

def signup(request):
    # signup 으로 POST 요청이 왔을 때, 새로운 유저를 만드는 절차를 밟는다.
    if request.method == 'POST':
        # password와 confirm에 입력된 값이 같다면
        if request.POST['password'] == request.POST['confirm']:
            # user 객체를 새로 생성
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            # 로그인 한다
            auth.login(request, user)
            return redirect('/home')
    # signup으로 GET 요청이 왔을 때, 회원가입 화면을 띄워준다.
    return render(request, 'blog/signup.html')

# 로그인
def login(request):
    # login으로 POST 요청이 들어왔을 때, 로그인 절차를 밟는다.
    if request.method == 'POST':
        # login.html에서 넘어온 username과 password를 각 변수에 저장한다.
        username = request.POST['username']
        password = request.POST['password']

        # 해당 username과 password와 일치하는 user 객체를 가져온다.
        user = auth.authenticate(request, username=username, password=password)
        
        # 해당 user 객체가 존재한다면
        if user is not None:
            # 로그인 한다
            auth.login(request, user)
            return redirect('/home')
        # 존재하지 않는다면
        else:
            # 딕셔너리에 에러메세지를 전달하고 다시 login.html 화면으로 돌아간다.
            return render(request, 'blog/login.html', {'error' : 'username or password is incorrect.'})
    # login으로 GET 요청이 들어왔을때, 로그인 화면을 띄워준다.
    else:
        return render(request, 'blog/login.html')

# 로그 아웃
def logout(request):
    # logout으로 POST 요청이 들어왔을 때, 로그아웃 절차를 밟는다.
    if request.method == 'POST':
        auth.logout(request)
        return redirect('/home')

    # logout으로 GET 요청이 들어왔을 때, 로그인 화면을 띄워준다.
    return render(request, 'blog/login.html')

# 회원 정보 수정
def mypage(request):
    if request.method == "POST":
        user = request.user
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        user.save()
        return redirect('/')
    return render(request, 'blog/mypage.html')

# 회원 탈퇴
def member_del(request):
    if request.method == "POST":
        pw_del = request.POST["pw_del"]
         # 해당 username과 password와 일치하는 user 객체를 가져온다.
        user = auth.authenticate(request, username=request.user, password=pw_del)
        print(user)
        # 해당 user 객체가 존재한다면
        if user is not None:
            # 로그인 한다
            user.delete()
            return redirect('/home')
    return render(request, 'blog/mypage.html')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>Web Service programming blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css">
  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css"
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <!--bootstrap js 추가 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<style>
  div.page-header{
    background-image: url("{% static 'background.png' %}");
  }
</style>

<body>
  {% if user.is_authenticated %}
    <ul class="nav" style="background-color: black;">
      <li class="nav-item">
          <a class="nav-link" style="color: white;"> 반가워요, {{ user.last_name }} 님! </a>
      </li>
      <li class="nav-item">
          <a class="nav-link" style="color: white;" href= "{% url 'mypage' %}">MyPage</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="color: white;" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
      </li>
    </ul>
    <form id="logout" method="POST" action="{% url 'logout' %}">
        {% csrf_token %} <input type="hidden" />
    </form>
  {% else %}
    <ul class="nav" style="background-color: black;">
      <li class="nav-item">
        <a class="nav-link" style="color: white;" href="{% url 'signup' %}">회원가입</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="color: white;" href="{% url 'login' %}">로그인</a>
      </li>
    </ul>
  {% endif %}
  <div>
    <div class="page-header">
      <div class="container-fluid" style=" padding: 22px;">
        <div class="navbar-brand" style="float: left;">
          <a href="/" class="nav-link" style="color: black;">
            <h1>Yoon's Blog</h1>
          </a>
        </div>
        <nav class="navbar navbar-light d-flex flex-row-reverse">
          <div>
            <div class="navbar">
              <ul class="nav">
                <li class="nav-item">
                  <a class="nav-link" href="/home">
                    <h4>Home</h4>
                  </a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'post_list' %}">
                    <h4>Blog</h4>
                  </a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </div>
  <hr style=" border: 2px solid #4263eb" />
  {% block login %}
  {% endblock %}
  <div>
  <div class="content container">
    <div class="row">
        {% block content %}
        {% endblock%}
    </div>
  </div>
  </div>
</body>

</html>

blog/templates/blog/home_page.html
{% extends 'blog/base.html' %}
{% block content %}
  This is HomePage!<br>
  Now Comming Soon...
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block login %}
<div class="w-25 border border-info border-3" style="position: absolute; left: 37%; top: 33%;">
  <div>
    <div style="padding-top: 5%; padding-left: 5%;">
          <h3 class="panel-title">로그인</h3>
        </div>
          <div class="panel-body">
            <form role="form" action="{% url 'login' %}" id="login_form" method="post">
              {% csrf_token %}
              <fieldset>
                <div class="w-100" style="padding-left: 5%; padding-right: 5%;">
                  <label for="login" class="form-label">ID</label>
                  <input class="form-control" placeholder="ID" name="username" type="text" autofocus="" required="">
                </div>
                <div class="w-100 p-3">
                  <label for="password" class="form-label">Password</label>
                  <input class="form-control" placeholder="Password" name="password" type="password" value=""
                    required="">
                </div>
                <!-- Change this to a button or input when using this as a form -->
                <div class="d-grid gap-2 col-11 mx-auto p-2" style="margin-bottom: 20px;">
                  <input type="submit" class="btn btn-lg btn-success btn-block" value="로그인">
                </div>
              </fieldset>
            </form>
          </div>
        </div>
  </div>
</div>
<script type="text/javascript">
  (function () {
    $(document).ready(function () {
      $('#login_form').submit(function () {
        var $usernameInput = $('#login_form input[name=username]');
        var $passwordInput = $('#login_form input[name=password]');
        if (!$usernameInput.val()) {
          alert("아이디를 입력해주세요.");
          $usernameInput.focus();
          return false;
        }
        if (!$passwordInput.val()) {
          alert("패스워드를 입력해주세요.");
          $passwordInput.focus();
          return false;
        }
        return true;
      });
    });
  })();
</script>
{% endblock %}

blog/templates/blog/main_page.html
{% load static %}
    <!doctype html>
    <html lang="en">
    
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
      <meta name="generator" content="Hugo 0.83.1">
      <title>Yoon's Blog</title>

      <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/jumbotron/">
      
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
      <link rel="stylesheet" type="text/css"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
      <!--bootstrap js 추가 -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
      <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

      <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
    
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
        div.blogimg2 {
          background-image: url("{% static 'blogimg2.png' %}");
        }
        img.blogimg{
          width: 500px;
        }
        .github-img{
          width: 150px;
        }
      </style>
    
    
    </head>
    
    <body>
    
      <main>
        <div class="container py-4">
          <header class="pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
              <span class="fs-2"><strong>Yoon's Blog</strong></span>
            </a>
          </header>
    
          <div class="p-5 mb-4 bg-light rounded-3 blogimg2">
            <div class="container-fluid py-5" style="position: relative;">
              <h1 class="display-5 fw-bold" style="color: white;">Show My Blog!</h1>
              <p class="col-md-8 fs-4" style="color: white;">게시글을 작성할 수 있는 블로그 페이지로 접속할 수 있습니다.</p>
              <a class="btn btn-outline-light btn-lg" href="{% url 'post_list' %}" type="button">들어가기</a>
              <div class="blog-img"></div>
              <div style="position: absolute; top:0%; right: 0%; box-shadow: 1px 3px 3px 1px rgba(0, 0, 0, 0.4);">
                <img class="blogimg" src="{% static 'blogimg.png' %}" />
              </div>
            </div>
          </div>
    
          <div class="row align-items-md-stretch">
            <div class="col-md-6">
              <div class="h-100 p-5 text-white bg-dark rounded-3">
                <h2>Yoon's Github</h2>
                <div style="vertical-align: middle">
                  <img class="github-img" style="float: left; margin-right: 10px;"src="{% static 'github.png' %}" />
                  <div><strong>Id</strong> : syoon0624<br>
                  <strong>Language</strong> : javascript, HTML, CSS, Python, C++<br>
                  <strong>Usable stack</strong> : React.js, HTML5, Django framework, Node.js<br>
                  <strong>Repositories</strong> : WebServiceProgramming, myCookBook, pymodi, ...
                  </div><br><br>
                </div>
                <a href="https://github.com/syoon0624" class="btn btn-outline-light" type="button">살펴보기</a>
              </div>
            </div>
            <div class="col-md-6">
              <div class="h-100 p-5 bg-light border rounded-3">
                <h2>Yoon's Profile</h2>
                <img class="github-img" style="float: left; box-shadow: 1px 3px 3px 1px rgba(0, 0, 0, 0.4); margin-right: 10px;" src="{% static 'profile.png' %}" />
                <h5><strong>이름 </strong> : 이승윤 <br>
                <strong>생년월일 </strong> : 1996-06-24 <br><br>
                <strong>Now</strong> : 경희대학교 컴퓨터공학과 4학년 <br>
                <strong>분야</strong> : Frontend / Web Programming <br>
                <strong>개발/공부중</strong> : React.js, Javascript ES6 ... <br>
                <strong>Contact Me</strong> : syoon624@naver.com 또는 <br>
                syoon0624@khu.ac.kr
                </h5>
              </div>
            </div>
          </div>
    
          <footer class="pt-3 mt-4 text-muted border-top">
            &copy; 2021 WebService Programming Project
          </footer>
        </div>
      </main>

blog/templates/blog/mypage.html
{% extends 'blog/base.html' %}

{% block content %}
  <div>
    <div style="padding-top: 5%; padding-left: 5%;">
      <h3 class="panel-title">회원수정</h3>
    </div>
    <div class="panel-body">
      <form role="form" action="{% url 'mypage' %}" id="mypage_form" method="POST">
        {% csrf_token %}
        <fieldset>
          <div class="w-100" style="padding-left: 5%; padding-right: 5%; margin-top: 10px;">
            ID : {{user}}
          </div>
          <div class="w-100" style="padding-left: 5%; padding-right: 5%;padding-top: 3%; margin-top: 10px;">
            성 : <input class="form-control" placeholder="First name" name="first_name" value="{{user.first_name}}" required="">
          </div>
          <div class="w-100" style="padding-left: 5%; padding-right: 5%;padding-top: 3%; margin-top: 10px;">
            이름 : <input class="form-control" placeholder="Last name" name="last_name" value="{{user.last_name}}" required="">
          </div>
          <div class="w-100" style="padding-left: 5%; padding-right: 5%;padding-top: 3%; margin-top: 10px;">
            이메일 : <input class="form-control" placeholder="E-mail" name="email" value="{{user.email}}" required="">
          </div>
          <!-- Change this to a button or input when using this as a form -->
          <div class="d-grid gap-2 col-11 mx-auto p-2">
            <input type="submit" class="btn btn-lg btn-success btn-block" style="margin-top: 10px; margin-bottom: 10px;"
              value="수정하기">
          </div>
        </fieldset>
      </form>
      <div id="comment" style="margin-bottom: 30px;" class="container">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-default" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
                aria-controls="collapseTwo">
                <strong>회원 탈퇴하기</strong>
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingOne" data-parent="#comment">
            <div class="card-body">
              <form method="POST" action="{% url 'member_del' %}" class="post-form">
                {% csrf_token %}
                비밀번호 : <input type="password" class="form-control" name="pw_del" placeholder="비밀번호를 입력해주세요."/>
                <div style="text-align: right; margin-top: 10px;">
                  <button type="submit" class="btn btn-success">탈퇴</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock%}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}

<form action="" method="POST">
  {% csrf_token %}
  <div class="card">
    <div class="card-header">
      <input type="text" name="title" style="width: 100%;background-color:transparent; border: transparent; border-bottom: 1px solid #339af0;" placeholder="제목을 입력해주세요.">
    </div>
    <div>
      {{ form.text }}
    </div>
  </div>

  <div class="text-right">
    <button type="submit" id="write" class="btn btn-dark" style="margin-top: 10px; margin-bottom: 10px;">작성하기</button>
  </div>
</form>

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.js"></script>
<script type="text/javascript" src="/static/js/lang/summernote-ko-KR.js"></script>

<script>
  $(document).ready(function () {
    $('#id_text').summernote({
      placeholder: '내용을 입력해주세요.',
      height: 500,
      minHeight: 500,
      maxHeight: 500,
      lang: 'ko-KR',

      toolbar: [
        ['style', ['style']],
        ['font', ['bold', 'underline', 'clear']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video']],
        ['view', ['fullscreen', 'help']]
      ]
    });
    $('p').css('margin-bottom', '0')
    $('.note-resizebar').css('display', 'none');
  });
</script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="col-md-11">
    <a href="{% url 'post_new' %}" style="position: fixed; bottom: 7%; right: 4%;"><svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-plus-circle-fill"
        viewBox="0 0 16 16">
        <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z" />
    </svg></a>
    {% for post in posts %}
    <div class="card" style="margin-bottom: 20px; box-shadow: 1px 3px 3px 1px rgba(0, 0, 0, 0.4);">
        <h4 class="card-header" style="padding: 15px; background-color: #e7f5ff;">{{ post.title}}</h5>
        <div class="card-body">
            <h6 class="card-title" style="color: #868e96;">작성일: {{ post.published_date }}</h5>
            <span class="card-text" style="display:inline-block; max-width:400px; max-height: 100px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">{{ post.text|safe }}</span>
            <br>
            <a href="{% url 'post_detail' pk=post.pk %}">댓글: {{ post.approved_comments.count }}</a>
            <div style="text-align: right;">
                <a href="{% url 'post_detail' pk=post.pk%}" class="btn btn-primary">자세히 보기</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}